import { InstrumentSchema } from "@plutus/domain";

import { fixtureIds, fixtureNow } from "./ids";

const instrumentEntries = {
  AAPL: {
    id: fixtureIds.AAPL,
    assetType: "stock",
    canonicalSymbol: "AAPL",
    displaySymbol: "AAPL",
    name: "Apple Inc.",
    sector: "Technology",
    category: "Mega-cap equity",
    market: "NASDAQ",
    region: "US",
    currency: "USD",
    exchange: "XNAS",
    providerRefs: { fixture: "AAPL" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  NVDA: {
    id: fixtureIds.NVDA,
    assetType: "stock",
    canonicalSymbol: "NVDA",
    displaySymbol: "NVDA",
    name: "NVIDIA Corporation",
    sector: "Technology",
    category: "Semiconductors",
    market: "NASDAQ",
    region: "US",
    currency: "USD",
    exchange: "XNAS",
    providerRefs: { fixture: "NVDA" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  BTC: {
    id: fixtureIds.BTC,
    assetType: "crypto",
    canonicalSymbol: "BTC",
    displaySymbol: "BTC",
    name: "Bitcoin",
    sector: null,
    category: "Digital asset",
    market: "crypto",
    region: "global",
    currency: "USD",
    exchange: null,
    providerRefs: { fixture: "BTC-USD" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  ETH: {
    id: fixtureIds.ETH,
    assetType: "crypto",
    canonicalSymbol: "ETH",
    displaySymbol: "ETH",
    name: "Ethereum",
    sector: null,
    category: "Digital asset",
    market: "crypto",
    region: "global",
    currency: "USD",
    exchange: null,
    providerRefs: { fixture: "ETH-USD" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  USDC: {
    id: fixtureIds.USDC,
    assetType: "stablecoin",
    canonicalSymbol: "USDC",
    displaySymbol: "USDC",
    name: "USD Coin",
    sector: null,
    category: "Stablecoin",
    market: "crypto",
    region: "global",
    currency: "USD",
    exchange: null,
    providerRefs: { fixture: "USDC-USD" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  USD: {
    id: fixtureIds.USD,
    assetType: "cash",
    canonicalSymbol: "USD",
    displaySymbol: "USD",
    name: "US Dollar Cash",
    sector: null,
    category: "Cash",
    market: null,
    region: "US",
    currency: "USD",
    exchange: null,
    providerRefs: { fixture: "USD-CASH" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  SPY: {
    id: fixtureIds.SPY,
    assetType: "etf",
    canonicalSymbol: "SPY",
    displaySymbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    sector: null,
    category: "Broad market ETF",
    market: "NYSE Arca",
    region: "US",
    currency: "USD",
    exchange: "ARCX",
    providerRefs: { fixture: "SPY" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
  QQQ: {
    id: fixtureIds.QQQ,
    assetType: "etf",
    canonicalSymbol: "QQQ",
    displaySymbol: "QQQ",
    name: "Invesco QQQ Trust",
    sector: null,
    category: "Technology-heavy ETF",
    market: "NASDAQ",
    region: "US",
    currency: "USD",
    exchange: "XNAS",
    providerRefs: { fixture: "QQQ" },
    status: "active",
    createdAt: fixtureNow,
    updatedAt: fixtureNow,
  },
} as const;

export const instrumentMap = Object.fromEntries(
  Object.entries(instrumentEntries).map(([symbol, instrument]) => [
    symbol,
    InstrumentSchema.parse(instrument),
  ]),
) as {
  [Symbol in keyof typeof instrumentEntries]: ReturnType<
    typeof InstrumentSchema.parse
  >;
};

export const instruments = Object.values(instrumentMap);
