export const CCXT_EXCHANGE_IDS = [
  "aftermath",
  "alpaca",
  "apex",
  "arkham",
  "ascendex",
  "aster",
  "backpack",
  "bequant",
  "bigone",
  "binance",
  "binancecoinm",
  "binanceus",
  "binanceusdm",
  "bingx",
  "bit2c",
  "bitbank",
  "bitbns",
  "bitfinex",
  "bitflyer",
  "bitget",
  "bithumb",
  "bitmart",
  "bitmex",
  "bitopro",
  "bitrue",
  "bitso",
  "bitstamp",
  "bitteam",
  "bittrade",
  "bitvavo",
  "blockchaincom",
  "blofin",
  "btcbox",
  "btcmarkets",
  "btcturk",
  "bullish",
  "bybit",
  "bybiteu",
  "bydfi",
  "cex",
  "coinbase",
  "coinbaseadvanced",
  "coinbaseexchange",
  "coinbaseinternational",
  "coincheck",
  "coinex",
  "coinmate",
  "coinmetro",
  "coinone",
  "coinsph",
  "coinspot",
  "cryptocom",
  "cryptomus",
  "deepcoin",
  "delta",
  "deribit",
  "derive",
  "digifinex",
  "dydx",
  "exmo",
  "fmfwio",
  "foxbit",
  "gate",
  "gateio",
  "gemini",
  "grvt",
  "hashkey",
  "hibachi",
  "hitbtc",
  "hollaex",
  "htx",
  "huobi",
  "hyperliquid",
  "independentreserve",
  "indodax",
  "kraken",
  "krakenfutures",
  "kucoin",
  "kucoinfutures",
  "latoken",
  "lbank",
  "lighter",
  "luno",
  "mercado",
  "mexc",
  "modetrade",
  "myokx",
  "ndax",
  "novadax",
  "okx",
  "okxus",
  "onetrading",
  "oxfun",
  "p2b",
  "pacifica",
  "paradex",
  "paymium",
  "phemex",
  "poloniex",
  "tokocrypto",
  "toobit",
  "upbit",
  "wavesexchange",
  "weex",
  "whitebit",
  "woo",
  "woofipro",
  "xt",
  "yobit",
  "zaif",
  "zebpay",
] as const;

export type CcxtExchangeId = (typeof CCXT_EXCHANGE_IDS)[number];

const CCXT_EXCHANGE_ID_SET: ReadonlySet<string> = new Set(CCXT_EXCHANGE_IDS);

const DISPLAY_NAME_OVERRIDES: Readonly<Record<string, string>> = {
  binancecoinm: "Binance COIN-M",
  binanceus: "Binance US",
  binanceusdm: "Binance USD-M",
  bitvavo: "Bitvavo",
  blockchaincom: "Blockchain.com",
  btcmarkets: "BTC Markets",
  coinbaseadvanced: "Coinbase Advanced",
  coinbaseexchange: "Coinbase Exchange",
  coinbaseinternational: "Coinbase International",
  cryptocom: "Crypto.com",
  dydx: "dYdX",
  fmfwio: "FMFW.io",
  gateio: "Gate.io",
  htx: "HTX",
  myokx: "MyOKX",
  okx: "OKX",
  okxus: "OKX US",
  p2b: "P2B",
  woo: "WOO X",
  woofipro: "WOOFi Pro",
  xt: "XT.com",
};

export function isCcxtExchangeId(exchangeId: string): exchangeId is CcxtExchangeId {
  return CCXT_EXCHANGE_ID_SET.has(exchangeId);
}

export function ccxtExchangeDisplayName(exchangeId: string): string {
  return DISPLAY_NAME_OVERRIDES[exchangeId] ?? titleCaseExchangeId(exchangeId);
}

function titleCaseExchangeId(exchangeId: string): string {
  return exchangeId
    .split(/(?=[0-9])|_/u)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
